M48
; DRILL file {KiCad (6.0.4)} date Thu Mar 24 17:42:49 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-03-24T17:42:49+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.4)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.700
%
G90
G05
T1
X83.5Y-53.5
X83.5Y-76.5
X141.5Y-53.5
X141.5Y-76.5
T0
M30
